export const skillsData = {
  frontend: [
    { name: "JavaScript", icon: "/assets/js.png" },
    { name: "React JS", icon: "/assets/react.png" },
    { name: "Next JS", icon: "/assets/nextjs.png" },
    { name: "Astro JS", icon: "/assets/astro.png" },
    { name: "Gatsby JS", icon: "/assets/gatsby.png" },
    { name: "Tailwind CSS", icon: "/assets/tailwind.png" },
    { name: "Material UI", icon: "/assets/mui.png" },
    { name: "Framer Motion", icon: "/assets/framer.png" },
    { name: "Sass", icon: "/assets/sass.png" },
    { name: "GSAP", icon: "/assets/gs.png" },
    { name: "ShadCN UI", icon: "/assets/scn.png" },
    { name: "Ant Design", icon: "/assets/ant.png" },
    { name: "Chakra UI", icon: "/assets/chak.png" },
    { name: "WebSocket", icon: "/assets/socket.png" },
    { name: "Redux", icon: "/assets/redux.png" },
    { name: "Zustand", icon: "/assets/suztand.png" },
  ],
  backend: [
    { name: "Node JS", icon: "/assets/nod.png" },
    { name: "Express JS", icon: "/assets/ex.png" },
    { name: "Nest JS", icon: "/assets/nest.png" },
    { name: "GraphQL", icon: "/assets/graphql.png" },
    { name: "REST API", icon: "/assets/rest.png" },
    { name: "PostgreSQL", icon: "/assets/pst.png" },
    { name: "MongoDB", icon: "/assets/mdb.png" },
    { name: "Strapi", icon: "/assets/strapi.png" },
    { name: "Prisma", icon: "/assets/ps.png" },
    { name: "Cloudflare", icon: "/assets/cl.png" },
  ],
  app: [
    { name: "React Native", icon: "/assets/react.png" },
    { name: "Expo", icon: "/assets/expo.png" },
    { name: "PWA", icon: "/assets/pwa.png" },
  ],
  devtools: [
    { name: "Vs Code", icon: "/assets/vs-code.png" },
    { name: "TypeScript", icon: "/assets/ts.png" },
    { name: "Zod", icon: "/assets/zod.png" },
    { name: "figma", icon: "/assets/fig.png" },
    { name: "docker", icon: "/assets/doc.png" },
    { name: "postman", icon: "/assets/postman.png" },
    { name: "Git", icon: "/assets/git.png" },
  ],
};
