export const experiences = [
  {
    company: "FlexLab Studio",
    role: "Sr.Software Developer",
    period: "Sep 2025 - Present",
    location: "USA (Remote)",
    icon: "/assets/flexlab.svg",
    details: [
      "Define the technology roadmap: which stacks, frameworks, platforms to adopt.",
      "Ensure the system is scalable, performant, maintainable as client acquisitions grow, as products expand in complexity, as traffic surges",
      "Evaluate and adopt emerging technologies where appropriate to keep differentiation.",
    ],
    technologies: ["React", "Node.js", "Next JS", "TypeScript", "Cloud Services"],
  },
  {
    company: "One-year Academy",
    role: "Frontend Developer (Contract)",
    period: "July 2025 - Sep 2025",
    location: "Bangladesh (Remote)",
    icon: "/assets/one-year.png",
    details: [
      "Define & implement core architecture and platform features",
      "Lead team of developers / coordinate modules",
      "Worked on their custom LMS / learning platform the system handled course content delivery, dashboards, student progress tracking, live class sessions, quizzes, and content updates.",
    ],
    technologies: ["React", "Node.js", "Next JS", "TypeScript", "Cloud Services"],
  },
  {
    company: "StepUp Soft",
    role: "Senior Software Developer",
    period: "Dec 2023 - June 2025",
    location: "Germany (Remote)",
    icon: "/assets/office02.png",
    details: [
      "Lead frontend development of Logensa SaaS, ensuring HIPAA, GDPR, and data privacy compliance",
      "Contributed to backend with NestJS, ensuring seamless integration and efficient data flow",
      "Built scalable, responsive UIs with UX and backend teams for healthcare workflows",
    ],
    technologies: [
      "React",
      "Next.js",
      "NestJS",
      "Healthcare Compliance",
      "TypeScript",
    ],
  },
  {
    company: "Created By Cocoon",
    role: "Full Stack Developer",
    period: "Nov 2021 - Dec 2023",
    location: "UK (Remote)",
    icon: "/assets/office03.png",
    details: [
      "Developed 7 projects using React, Next.js, Gatsby, Firebase, and more",
      "Lead frontend architecture and code reviews to ensure consistency and quality",
      "Contributed to backend with Node.js, Express, Shopify, and CRMs for full-stack delivery",
    ],
    technologies: [
      "React",
      "Next.js",
      "Gatsby",
      "Firebase",
      "Node.js",
      "Three JS",
    ],
  },
  {
    company: "Creative Business Group",
    role: "Full Stack Developer",
    period: "Oct 2020 - Nov 2021",
    location: "Bangladesh (On-site)",
    icon: "/assets/office04.png",
    details: [
      "Developed frontend and backend for a SaaS Call Management System to optimize customer communication",
      "Built React Native features for real-time call handling and notifications",
      "Built scalable APIs with Node.js and Express for smooth data sync",
    ],
    technologies: [
      "React",
      "React Native",
      "Node.js",
      "Express",
      "Real-time APIs",
    ],
  },
  {
    company: "Doatkolom",
    role: "Full Stack Developer",
    period: "Jan 2018 - Oct 2020",
    location: "Bangladesh (Remote)",
    icon: "/assets/office05.png",
    details: [
      "Built scalable, responsive frontends using modern JS frameworks and tools",
      "Built custom, dynamic UIs with ReactJS for intuitive editing experiences",
      "Integrated Firebase and Algolia in backend services using Node.js and Express",
    ],
    technologies: ["React", "Node.js", "Express", "Firebase", "Algolia"],
  },
];
