export const experiences = [
  {
    company: "FlexLab Studio (Contract)",
    role: "Senior Software Developer",
    period: "Sep 2025 - Present",
    location: "USA (Remote)",
    icon: "/assets/flexlab.svg",
    details: [
      "Spearheading development of high-impact client products for enterprise-grade performance, maintainability, and scalability using React, Node.js, and Next.js.",
      "Collaborating directly with founders and technical directors to define long-term architectural blueprints, set coding standards, and select optimal technologies for future scalability.",
      "Establishing CI/CD pipelines, implementing cloud infrastructure automation, and optimizing build processes for deployment speed and reliability.",
      "Mentoring mid-level developers through pair-programming sessions and code reviews, introducing advanced TypeScript patterns and component-driven design principles.",
      "Leading initiatives to modernize legacy React codebases with server-side rendering (SSR), hybrid rendering patterns, and improved caching strategies.",
      "Integrating analytics and A/B testing systems to measure real-world user impact, guiding continuous product improvement based on real data.",
    ],
    technologies: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "AWS",
      "CI/CD",
      "Cloud Services",
      "Performance Optimization",
    ],
  },

  {
    company: "One-Year Academy (One-time project)",
    role: "Frontend Developer",
    period: "July 2025 - Sep 2025",
    location: "Bangladesh (Remote)",
    icon: "/assets/one-year.png",
    details: [
      "Led the complete frontend development of a custom Learning Management System (LMS) for One-Year Academy, tailored to handle student registration, course progress tracking, live sessions, and performance analytics.",
      "Architected a modular React component library with full dark/light mode support, drastically reducing UI duplication and improving developer velocity.",
      "Built dynamic dashboards for instructors and learners, integrating real-time course updates and WebSocket-based communication for live classes.",
      "Collaborated with backend and product teams to design an API layer optimized for scalability and smooth data synchronization across multiple user roles.",
      "Optimized image loading and bundle sizes through code-splitting, lazy loading, and prefetch strategies — improving page speed by over 40%.",
    ],
    technologies: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Redux Toolkit",
      "WebSocket",
      "Firebase",
      "Cloud Storage",
    ],
  },

  {
    company: "StepUp Soft",
    role: "Senior Software Developer",
    period: "Dec 2023 - June 2025",
    location: "Germany (Remote)",
    icon: "/assets/office02.png",
    details: [
      "Served as lead frontend engineer for Logensa — a healthcare SaaS platform ensuring HIPAA and GDPR compliance, focusing on security, scalability, and accessibility.",
      "Developed modular React architecture with optimized SSR via Next.js to handle thousands of daily active users with near-instant load times.",
      "Collaborated with backend teams to design RESTful and GraphQL APIs using NestJS, ensuring clean data flow and type-safe communication across the stack.",
      "Integrated robust form validation and encryption protocols to safeguard sensitive patient data.",
      "Partnered closely with UI/UX designers to translate complex workflows into clean, user-friendly interfaces for clinicians and administrators.",
      "Implemented role-based access control and real-time dashboards for analytics and patient management, drastically improving data visibility for clients.",
    ],
    technologies: [
      "React",
      "Next.js",
      "NestJS",
      "TypeScript",
      "GraphQL",
      "Healthcare Compliance",
      "AWS Lambda",
      "PostgreSQL",
    ],
  },

  {
    company: "Created By Cocoon",
    role: "Full Stack Developer",
    period: "Nov 2021 - Dec 2023",
    location: "UK (Remote)",
    icon: "/assets/office03.png",
    details: [
      "Worked as a full-stack developer for multiple global clients, delivering 7+ production-ready products across web, mobile, and PWA platforms.",
      "Built reusable front-end architectures with Next.js, Gatsby, and React — integrating Firebase and Node.js backends for seamless user experiences.",
      "Implemented SSR and SSG strategies to improve SEO performance and reduce load times by up to 60%.",
      "Created real-time admin dashboards for eCommerce and marketing platforms using React Query, WebSocket, and Redux Toolkit.",
      "Contributed to backend logic for Shopify integrations, marketing CRMs, and custom API endpoints using Express and MongoDB.",
      "Set up automated testing and linting pipelines to enforce quality assurance across all projects.",
    ],
    technologies: [
      "React",
      "Next.js",
      "Gatsby",
      "Firebase",
      "Node.js",
      "Express",
      "Shopify API",
      "Three.js",
      "MongoDB",
    ],
  },

  {
    company: "Creative Business Group",
    role: "Full Stack Developer",
    period: "Oct 2020 - Nov 2021",
    location: "Bangladesh (On-site)",
    icon: "/assets/office04.png",
    details: [
      "Developed a complete SaaS-based Call Management System to optimize inbound and outbound customer communication for enterprise clients.",
      "Engineered real-time call dashboards using WebSocket and React Native to provide live updates for customer support teams.",
      "Built scalable APIs with Node.js and Express, integrating Redis caching and socket.io for seamless event-driven communication.",
      "Implemented detailed analytics features, giving management teams visibility into agent performance and call resolution efficiency.",
      "Optimized server queries, cutting response latency by 35% and increasing concurrent connection handling capacity.",
      "Led weekly code reviews and contributed to internal toolkits that standardized React/Node boilerplates for future company projects.",
    ],
    technologies: [
      "React",
      "React Native",
      "Node.js",
      "Express",
      "Redis",
      "Socket.io",
      "MongoDB",
      "AWS EC2",
    ],
  },

  {
    company: "Doatkolom",
    role: "Full Stack Developer",
    period: "Jan 2018 - Oct 2020",
    location: "Bangladesh (Remote)",
    icon: "/assets/office05.png",
    details: [
      "Joined early-stage startup as a founding developer, building their digital publishing platform from concept to live production.",
      "Developed a modern, scalable frontend architecture using ReactJS, designed for easy content management and real-time editing.",
      "Created server-side Node.js APIs integrated with Firebase and Algolia to enable instant content search and multi-device syncing.",
      "Built a collaborative editor system where multiple users could write, edit, and publish simultaneously — boosting team productivity.",
      "Introduced CI/CD workflows and containerized deployment strategies (Docker + Nginx), ensuring consistent builds and rollbacks.",
      "Collaborated closely with designers and founders to evolve UX/UI and brand consistency as user base scaled.",
    ],
    technologies: [
      "React",
      "Node.js",
      "Express",
      "Firebase",
      "Algolia",
      "Docker",
      "Nginx",
      "CI/CD",
    ],
  },
];
