export const experiences = [
  {
    company: "CampiX.AI",
    role: "Senior Software Developer",
    period: "July 2025 - Present",
    location: "United States (Remote)",
    icon: "/assets/campix-logo.png",
    details: [
      "Leading development of AI-powered applications with modern JavaScript frameworks",
      "Implementing scalable solutions for machine learning integration",
      "Collaborating with cross-functional teams to deliver innovative AI products",
    ],
    technologies: ["React", "Node.js", "AI/ML", "TypeScript", "Cloud Services"],
  },
  {
    company: "StepUp Soft",
    role: "Senior Software Developer",
    period: "Dec 2023 - June 2025",
    location: "Germany (Remote)",
    icon: "/assets/stepup-logo.png",
    details: [
      "Lead frontend development of Logensa SaaS, ensuring HIPAA, GDPR, and data privacy compliance",
      "Contributed to backend with NestJS, ensuring seamless integration and efficient data flow",
      "Built scalable, responsive UIs with UX and backend teams for healthcare workflows",
    ],
    technologies: [
      "React",
      "Next.js",
      "NestJS",
      "Healthcare Compliance",
      "TypeScript",
    ],
  },
  {
    company: "Created By Cocoon",
    role: "Senior Full Stack Developer",
    period: "Nov 2021 - Dec 2023",
    location: "UK (Remote)",
    icon: "/assets/cocoon-logo.png",
    details: [
      "Developed 7 projects using React, Next.js, Gatsby, Firebase, and more",
      "Lead frontend architecture and code reviews to ensure consistency and quality",
      "Contributed to backend with Node.js, Express, Shopify, and CRMs for full-stack delivery",
    ],
    technologies: [
      "React",
      "Next.js",
      "Gatsby",
      "Firebase",
      "Node.js",
      "Shopify",
    ],
  },
  {
    company: "Creative Business Group",
    role: "Full Stack Developer",
    period: "Oct 2020 - Nov 2021",
    location: "Bangladesh (On-site)",
    icon: "/assets/cbg-logo.png",
    details: [
      "Developed frontend and backend for a SaaS Call Management System to optimize customer communication",
      "Built React Native features for real-time call handling and notifications",
      "Built scalable APIs with Node.js and Express for smooth data sync",
    ],
    technologies: [
      "React",
      "React Native",
      "Node.js",
      "Express",
      "Real-time APIs",
    ],
  },
  {
    company: "Doatkolom",
    role: "Full Stack Developer",
    period: "Jan 2018 - Oct 2020",
    location: "Bangladesh (Remote)",
    icon: "/assets/doatkolom-logo.png",
    details: [
      "Built scalable, responsive frontends using modern JS frameworks and tools",
      "Built custom, dynamic UIs with ReactJS for intuitive editing experiences",
      "Integrated Firebase and Algolia in backend services using Node.js and Express",
    ],
    technologies: ["React", "Node.js", "Express", "Firebase", "Algolia"],
  },
];
