export const testimonials = [
  {
    id: 1,
    rating: 5,
    title: "Excellent Service",
    text: "Azmir delivered a good result and supported us throughout the project.",
    name: "Arleigh",
    avatar: "/assets/Asset1.png",
  },
  {
    id: 2,
    rating: 5,
    title: "Good Work",
    text: "My first project with Azmir was smooth, fast, and perfectly executed.",
    name: "Nayeem A.K.M",
     avatar: "/assets/Asset2.png",
  },
  {
    id: 3,
    rating: 5,
    title: "Best Service",
    text: "Clear communication, great delivery, and strong technical knowledge.",
    name: "Raphael",
    avatar: "/assets/Asset4.png",
  },
  {
    id: 4,
    rating: 5,
    title: "Great Work",
    text: "Professional, responsive, and always focused on high-quality output.",
    name: "Luke",
    avatar: "/assets/Asset6.png",
  },
  {
    id: 5,
    rating: 5,
    title: "Good Experience",
    text: "Very skilled developer with an eye for detail and great consistency.",
    name: "Ali Al-mohammad",
     avatar: "/assets/Asset10.png",
  },
  {
    id: 6,
    rating: 5,
    title: "Good Work",
    text: "Efficient, reliable, and delivered exactly what was promised on time.",
    name: "Kamrul Islam Chowdhury",
     avatar: "/assets/Asset2.png",
  },
  {
    id: 7,
    rating: 5,
    title: "Best Service",
    text: "Azmir handled the project with care, skill, and clear communication.",
    name: "Mathew",
    avatar: "/assets/Asset10.png",
  },
  {
    id: 8,
    rating: 5,
    title: "Good Work",
    text: "Delivered clean, optimized code with impressive speed and precision.",
    name: "Safir Ahmed",
    avatar: "/assets/Asset4.png",
  },
  {
    id: 9,
    rating: 5,
    title: "Great Experience",
    text: "Azmir’s work improved our app performance and UX significantly.",
    name: "Samantha",
     avatar: "/assets/Asset5.png",
  },
  {
    id: 10,
    rating: 5,
    title: "Excellent Service",
    text: "Outstanding developer who turns ideas into fast, reliable products.",
    name: "Adrian",
     avatar: "/assets/Asset2.png",
  },
];
