export const ProcessData = [
  {
    step: 1,
    title: "Requirement Analysis",
    width: 150,
    height: 150,
    desc: "Understand client goals, audience pain points, and project scope. This step includes requirement gathering sessions, competitor research, and defining clear success metrics before a single line of code is written.",
    img: "/assets/analysis.webp",
  },
  {
    step: 2,
    title: "Planning & Architecture",
    width: 100,
    height: 100,
    desc: "Translate insights into a structured technical plan. Define frontend and backend architecture, database relationships, and APIs. Every component and dependency is chosen for scalability and maintainability.",
    img: "/assets/planning.webp",
  },
  {
    step: 3,
    title: "API & Database Design",
    width: 80,
    height: 80,
    desc: "Design RESTful or GraphQL APIs with secure endpoints and efficient query patterns. Set up well-structured MongoDB schemas ensuring consistency, performance, and easy future migrations.",
    img: "/assets/api.png",
  },
  {
    step: 4,
    title: "Full-Stack Development",
    width: 100,
    height: 100,
    desc: "Build dynamic frontend interfaces with React or Next.js and powerful backend logic with Node.js and Express. Integrate APIs, implement authentication, and make sure every feature feels fast and intuitive.",
    img: "/assets/dev.png",
  },
  {
    step: 5,
    title: "Testing & Debugging",
    width: 80,
    height: 80,
    desc: "Run comprehensive unit and integration tests. Use tools like Jest or Cypress to catch regressions early. Optimize code, fix edge cases, and ensure smooth performance across all devices and browsers.",
    img: "/assets/testing.webp",
  },
  {
    step: 6,
    title: "Deployment & Monitoring",
    width: 140,
    height: 140,
    desc: "Deploy the application to production using platforms like Vercel, AWS, or DigitalOcean. Set up real-time monitoring, error tracking, and analytics to ensure stability, uptime, and ongoing performance.",
    img: "/assets/dep.webp",
  },
];
