export const ProcessData = [
  {
    step: 1,
    title: "Requirement Analysis",
    width: 150,
    height: 150,
    desc: "understand client goals and user needs to define clear, achievable project objectives.",
    img: "/assets/analysis.webp",
  },
  {
    step: 2,
    title: "Planning & Architecture",
    width: 100,
    height: 100,
    desc: "design scalable backend and frontend architecture with the right tools and technologies.",
    img: "/assets/planning.webp",
  },
  {
    step: 3,
    title: "API & Database Design",
    width: 80,
    height: 80,
    desc: "structure robust RESTful APIs and design efficient database schemas with MongoDB.",
    img: "/assets/api.png",
  },
  {
    step: 4,
    title: "Full-Stack Development",
    width: 100,
    height: 100,
    desc: "develop frontend with React/Next.js and backend with Node.js/Express, ensuring seamless integration.",
    img: "/assets/dev.png",
  },
  {
    step: 5,
    title: "Testing & Debugging",
    width: 80,
    height: 80,
    desc: "conduct unit, integration, and end-to-end testing to ensure bug-free and performant apps.",
    img: "/assets/testing.webp",
  },
  {
    step: 6,
    title: "Deployment & Monitoring",
    width: 140,
    height: 140,
    desc: "deploy applications on cloud platforms and monitor for uptime, performance, and security.",
    img: "/assets/dep.webp",
  },
];
